# Generated by Django 5.2 on 2026-05-20 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paneles', '0002_columnaestado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_actividad', models.CharField(max_length=180)),
                ('descripcion_detallada', models.TextField(blank=True, null=True)),
                ('prioridad_actividad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('posicion_actividad', models.PositiveIntegerField(default=0)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('actividad_archivada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('columna_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_asociadas', to='paneles.columnaestado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de proyecto',
                'verbose_name_plural': 'Actividades de proyecto',
                'ordering': ['posicion_actividad', '-fecha_creacion'],
            },
        ),
    ]
