# Generated by Django 5.2 on 2026-05-20 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0002_miembroespacio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_panel', models.CharField(max_length=120, verbose_name='Nombre del panel')),
                ('descripcion_panel', models.TextField(blank=True, null=True)),
                ('posicion_visual', models.PositiveIntegerField(default=0)),
                ('panel_archivado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('espacio_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paneles_disponibles', to='espacios.espaciotrabajo')),
            ],
            options={
                'verbose_name': 'Panel de trabajo',
                'verbose_name_plural': 'Paneles de trabajo',
                'ordering': ['posicion_visual', 'id'],
            },
        ),
    ]
