# Generated by Django 5.2 on 2026-05-20 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_columna', models.CharField(max_length=80, verbose_name='Nombre de columna')),
                ('posicion_columna', models.PositiveIntegerField(default=0)),
                ('color_identificacion', models.CharField(default='gris', max_length=30)),
                ('columna_archivada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('panel_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas_kanban', to='paneles.paneltrabajo')),
            ],
            options={
                'verbose_name': 'Columna de estado',
                'verbose_name_plural': 'Columnas de estado',
                'ordering': ['posicion_columna', 'id'],
            },
        ),
    ]
