# Generated by Django 5.2 on 2026-05-20 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_espacio', models.CharField(max_length=120, verbose_name='Nombre del espacio')),
                ('descripcion_general', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('espacio_archivado', models.BooleanField(default=False)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Espacio de trabajo',
                'verbose_name_plural': 'Espacios de trabajo',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
