# Generated by Django 5.2 on 2026-05-20 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_participacion', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('COLABORADOR', 'Colaborador'), ('LECTOR', 'Lector')], default='COLABORADOR', max_length=20)),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('miembro_activo', models.BooleanField(default=True)),
                ('espacio_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_asociados', to='espacios.espaciotrabajo')),
                ('usuario_miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_participando', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro del espacio',
                'verbose_name_plural': 'Miembros de espacios',
                'unique_together': {('espacio_relacionado', 'usuario_miembro')},
            },
        ),
    ]
